// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../key/secret_key.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<_EncryptedSecretKey>>
abstract class EncryptedSecretKey implements RustOpaqueInterface {
  /// Decrypt secret key
  SecretKey decrypt({required String password});

  /// Parse from bech32
  static EncryptedSecretKey fromBech32({required String bech32}) => NostrSdk
      .instance.api
      .crateApiProtocolNipsNip49EncryptedSecretKeyFromBech32(bech32: bech32);

  /// Get encrypted secret key security
  EncryptedSecretKeySecurity keySecurity();

  /// Encrypt secret key
  factory EncryptedSecretKey(
          {required SecretKey secretKey,
          required String password,
          required int logN,
          required EncryptedSecretKeySecurity keySecurity}) =>
      NostrSdk.instance.api.crateApiProtocolNipsNip49EncryptedSecretKeyNew(
          secretKey: secretKey,
          password: password,
          logN: logN,
          keySecurity: keySecurity);

  /// Serialize to bech32
  String toBech32();

  /// Get encrypted secret key version
  EncryptedSecretKeyVersion version();
}

/// Key security
enum EncryptedSecretKeySecurity {
  /// The key has been known to have been handled insecurely (stored unencrypted, cut and paste unencrypted, etc)
  weak,

  /// The key has NOT been known to have been handled insecurely (stored encrypted, cut and paste encrypted, etc)
  medium,

  /// The client does not track this data
  unknown,
  ;
}

/// Encrypted Secret Key version (NIP49)
enum EncryptedSecretKeyVersion {
  v2,
  ;
}
